// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQsJm3Ixc4h8pp8K51TopVAhEA5G3ZIA4',
    appId: '1:614235530306:web:9ad87f5cead00d029af9db',
    messagingSenderId: '614235530306',
    projectId: 'musicbag-a78d7',
    authDomain: 'musicbag-a78d7.firebaseapp.com',
    storageBucket: 'musicbag-a78d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlaC8dQTcpKtIaL_mFj0XaONc6BIS_QXg',
    appId: '1:614235530306:android:f8cccd056f58a4a09af9db',
    messagingSenderId: '614235530306',
    projectId: 'musicbag-a78d7',
    storageBucket: 'musicbag-a78d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBgfvBwau_QP2gmY4SAwsgzkNn6NABcEw',
    appId: '1:614235530306:ios:7411984ebb4261309af9db',
    messagingSenderId: '614235530306',
    projectId: 'musicbag-a78d7',
    storageBucket: 'musicbag-a78d7.appspot.com',
    iosBundleId: 'com.example.mySoundPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBgfvBwau_QP2gmY4SAwsgzkNn6NABcEw',
    appId: '1:614235530306:ios:43b1f166ce74548a9af9db',
    messagingSenderId: '614235530306',
    projectId: 'musicbag-a78d7',
    storageBucket: 'musicbag-a78d7.appspot.com',
    iosBundleId: 'com.example.mySoundPlayer.RunnerTests',
  );
}
